### ISSUE TITLE
Options without parameters ("flags")

### ISSUE THREAD

**Issue by ronkot** [mattallty/Caporal.js#18]
Is it possible to define flag-like options that take zero parameters, e.g. `--verbose`? It seems that value following the option gets always assigned as option value and I haven't found a way around this behaviour.

**Comment by mattallty** [comment]
Hi @ronkot, thanks for your feedback.
Could you please try your case with the `fix-negative-number`branch ?

**Comment by mattallty** [comment]
Fixed in `master`.

**Comment by ronkot** [comment]
Sorry, I didn't have time to check the branch but great to hear that it's fixed!

Thanks!

**Comment by ronkot** [comment]
Hmm.. It seems that this problem still exists in master (#96f38f26165f365f7da7ff70b072d0d865916644). Here's a minimal example of the behavior:

```
#!/usr/bin/env node

const prog = require('caporal');
prog
  .version('1.0.0')
  .description('List dogs')
  .argument('[dogs...]', 'Dog list') 
  .option('--loud')
  .action(function(args, options, logger) {
    console.log('options', options, 'args', args)
    for (const dog of args.dogs) {
      logger.info(options.loud ? dog.toUpperCase() : dog)
    }
  });

prog.parse(process.argv);
```

And here's the output:
```
10:30 $ node test.js tex rex
options {} args { dogs: [ 'tex', 'rex' ] }
tex
rex

10:30 $ node test.js --loud tex rex
options { loud: 'tex' } args { dogs: [ 'rex' ] }
REX
```

So, I would like to get the following behavior:
```
10:30 $ node test.js --loud tex rex
options { loud: true } args { dogs: [ 'text', 'rex' ] }
TEX
REX
```

Is this possible with current caporal version? At least I haven't found a way to do this yet.

**Comment by mattallty** [comment]
Hi, currently `options`have to be passed *after* arguments. 
So `node test.js tex rex --loud` shoudl work.

**Comment by ronkot** [comment]
You are right, it works if `options` are defined after arguments. Maybe in future we are able to place options freely..? :)

Thanks for advice!
